version: '2'

#
# create a 3-node kafka cluster via docker
#
services:
  zk1:
    container_name: zk1
    image: minskey/kafka-zk
    working_dir: /usr/local/kafka/bin
    environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    ports:
      - 3001:2181
      - 3002:2888
      - 3003:3888

  zk2:
    container_name: zk2
    image: minskey/kafka-zk
    working_dir: /usr/local/kafka/bin
    environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    ports:
      - 4001:2181
      - 4002:2888
      - 4003:3888

  zk3:
    container_name: zk3
    image: minskey/kafka-zk
    working_dir: /usr/local/kafka/bin
    environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    ports:
      - 5001:2181
      - 5002:2888
      - 5003:3888

  kf1:
    container_name: kf1
    image: minskey/kafka-kf
    working_dir: /usr/local/kafka/bin
    environment:
      KF_BROKER_ID: 1
      KF_SERVER_PORT: 2181
      KF_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    ports:
      - 9001:9092
  kf2:
    container_name: kf2
    image: minskey/kafka-kf
    working_dir: /usr/local/kafka/bin
    environment:
      KF_BROKER_ID: 2
      KF_SERVER_PORT: 2181
      KF_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    ports:
      - 9002:9092

  kf3:
    container_name: kf3
    image: minskey/kafka-kf
    working_dir: /usr/local/kafka/bin
    environment:
      KF_BROKER_ID: 3
      KF_SERVER_PORT: 2181
      KF_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    ports:
      - 9003:9092

  producer:
    container_name: producer
    image: minskey/kafka-kf
    working_dir: /usr/local/kafka/bin
    entrypoint: /bin/bash  -c 'sleep 6000000'
    tty: true

  consumer:
    container_name: consumer
    image: minskey/kafka-kf
    tty: true
    working_dir: /usr/local/kafka/bin
    entrypoint: /bin/bash  -c 'sleep 6000000'
